# PRECISA CRIAR UMA NET EXTERNA 
# docker network create --scope=swarm --driver=overlay --attachable rabbitmq
# docker stack deploy -c docker-compose.yml rabbitmq
# Adicionar Label 
# docker node update --label-add rabbitmq1=true wekfvm5sly7z2t6qtmv5u2qlq
# docker node update --label-add rabbitmq2=true wekfvm5sly7z2t6qtmv5u2qlq
# docker node update --label-add rabbitmq3=true wekfvm5sly7z2t6qtmv5u2qlq
version: "3.6"
services:
  rabbitmq1:
    image: rabbitmq:local
    hostname: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_ERLANG_COOKIE="YSJSOIPIQHPEZQSUII"
      - RABBITMQ_NODENAME=rabbitmq
    networks:
      - prod
    volumes:
      - rabbitmq-01-data:/var/lib/rabbitmq     
    deploy:
      mode: global
      placement:
        constraints: [node.labels.rabbitmq1 == true]
  rabbitmq2:
      image: rabbitmq:local
      hostname: rabbitmq2
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
        - RABBITMQ_ERLANG_COOKIE="YSJSOIPIQHPEZQSUII"
        - RABBITMQ_NODENAME=rabbitmq
      networks:
        - prod
      volumes:
        - rabbitmq-02-data:/var/lib/rabbitmq
      deploy:
        mode: global
        placement:
          constraints: [node.labels.rabbitmq2 == true]
  rabbitmq3:
      image: rabbitmq:local
      hostname: rabbitmq3
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin
        - RABBITMQ_ERLANG_COOKIE="YSJSOIPIQHPEZQSUII"
        - RABBITMQ_NODENAME=rabbitmq
      networks:
        - prod
      volumes:
        - rabbitmq-03-data:/var/lib/rabbitmq
      deploy:
        mode: global
        placement:
          constraints: [node.labels.rabbitmq3 == true]
networks:
  prod:
    external: true
volumes:
  rabbitmq-01-data: 
  rabbitmq-02-data:
  rabbitmq-03-data:
